{{- if .Values.internalIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "user-portal.fullname" . }}-internal
  labels:
    {{- include "user-portal.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: gce-internal
    {{- if .Values.internalIngress.staticIpName }}
    kubernetes.io/ingress.regional-static-ip-name: {{ .Values.internalIngress.staticIpName | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.internalIngress.host | quote }}
      http:
        paths:
          - path: {{ .Values.internalIngress.path | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "user-portal.fullname" . }}
                port:
                  name: http
{{- end }}
