{{- if .Values.secretManager.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ default (include "user-portal.fullname" .) .Values.secretManager.providerClassName }}
  labels:
    {{- include "user-portal.labels" . | nindent 4 }}
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/{{ required "secretManager.projectId is required when secretManager.enabled=true" .Values.secretManager.projectId }}/secrets/{{ .Values.secretManager.appLoginSecretName }}/versions/latest"
        path: "{{ .Values.secretManager.appLoginFileName }}"
      - resourceName: "projects/{{ .Values.secretManager.projectId }}/secrets/{{ .Values.secretManager.mysqlSecretName }}/versions/latest"
        path: "{{ .Values.secretManager.mysqlFileName }}"
{{- end }}
