apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-portal.fullname" . }}
  labels:
    {{- include "user-portal.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and (not .Values.secretManager.enabled) (not .Values.config.existingSecret) }}
  MYSQL_PASSWORD: {{ .Values.config.mysqlPassword | quote }}
  {{- end }}
  FLASK_SECRET_KEY: {{ .Values.config.flaskSecretKey | quote }}
  {{- if not .Values.secretManager.enabled }}
  APP_LOGIN_USERNAME: {{ .Values.appLogin.username | quote }}
  {{- if .Values.appLogin.passwordHash }}
  APP_LOGIN_PASSWORD_HASH: {{ .Values.appLogin.passwordHash | quote }}
  {{- else }}
  APP_LOGIN_PASSWORD: {{ .Values.appLogin.password | quote }}
  {{- end }}
{{- end }}
